import csv
import os
import tkinter as tk
from tkinter import messagebox

# get working directory
script_path = os.path.abspath(__file__)
folder = os.path.dirname(script_path)

#startup program function that reads csv
participants = []
def readCSV():
    try:
        with open(f"{folder}/participants.csv",'r') as file:
            reader = csv.reader(file)
            next(reader)
            for line in reader:
                participants.append({"name": line[0],'surname': line[1],"age": int(line[2])})
    except:
        messagebox.showinfo("Hi Windows!", "participants.csv not found in folder") 
    # print(participants)

#selection sort function generated by ai
def selection_sort_by_age(group):
    n = len(group)
    for i in range(n):
        min_index = i
        for j in range(i + 1, n):
            if group[j]['age'] < group[min_index]['age']:
                min_index = j
        group[i], group[min_index] = group[min_index], group[i]

# function when button is pressed
def allocate():
    # get or create variables to be used
    global participants
    groups = {}
    teens = []
    seniors = [] 
    other = []
    size = spinBox.get()
    # print(amountOfGroups)
    #sort everyone by age into different lists
    for person in participants:
        if person['age'] <18:
            teens.append(person)
        elif person['age'] > 60:
            seniors.append(person)
        else:
            other.append(person)
    # print(teens)

    group_count = min(len(teens), len(seniors)) #assisted by ai
    # puts everyone in a group with the rules, creating a new group once current group is full
    for group in range(group_count):
        groups[group] = [teens[0], seniors[0]]
        teens.remove(teens[0]) 
        seniors.remove(seniors[0])
        # print(groups[group])
        try:
            while len(groups[group]) < int(size):
                groups[group].append(other[0])
                other.remove(other[0])
        except:
            # if no more people in list, put them back to be reused later
            for person in groups[group]:
                other.append(person)

    # print(len(groups[0]))
    # put leftovers into the same list as other
    if teens:
        for person in teens:
            other.append(person)
    if seniors:
        for person in seniors:
            other.append(person)
    # run the program again making sure to fill every group with user defined amount
    for group in range(group_count):
        try:
            while len(groups[group]) < int(size):
                groups[group].append(other[0])
                other.remove(other[0])
        except:
            # print(groups[group])
            for person in groups[group]:
                other.append(person)
    
    # print(groups)
    # prepare the text to show user
    messagetosend = ""
    for group in range(len(groups)):
        selection_sort_by_age(groups[group])
        messagetosend += f'''Team {group+1}:\n'''
        for person in range(len(groups[group])):
            name = groups[group][person]['name']
            surname = groups[group][person]['surname']
            age = groups[group][person]['age']
            messagetosend+=f"   {name} {surname} ({age})\n"
        messagetosend += f'''\n'''

    if other:
        messagetosend +="UNALLOCATED:\n"
        selection_sort_by_age(groups[group])
        for person in other:
            name = person['name']
            surname = person['surname']
            age = person['age']
            messagetosend+=f"   {name} {surname} ({age})\n"

    # print in the textbox, removing previous text
    readout.delete("1.0", tk.END)
    readout.insert(tk.END,messagetosend)

    # test prints
    # readout.insert(tk.END,groups)
    # readout.insert(tk.END,teens)
    # readout.insert(tk.END,seniors)
    # readout.insert(tk.END,adult)




# create GUI window
root = tk.Tk()
root.title("Team Allocator")
root.minsize(750,500)
root.maxsize(750,500)
# configure the grid for the tkinter window
root.columnconfigure(0,weight=3)
root.columnconfigure(1, weight=4)
root.rowconfigure(0, weight=2)
root.rowconfigure(1,weight=4)

# create widgets
teamLabel = tk.Label(root,text="Team size: ")
spinBox = tk.Spinbox(root, from_=4, to=8, width=2, relief="sunken")
allocatedLabel = tk.Label(root,text="Allocated teams:")
allocatedButton = tk.Button(root,text="Allocate",command=allocate) # button
textFrame = tk.Frame(root)
scrollBar = tk.Scrollbar(textFrame,orient=tk.VERTICAL)
readout = tk.Text(textFrame,width=80,height=30,yscrollcommand=scrollBar.set)
scrollBar.config(command=readout.yview)
textFrame.grid(row=1, column=1, sticky="NESW")
# place widgets
teamLabel.grid(row=0,column=0,sticky="W")
spinBox.grid(row=0,column=0,sticky="E")
allocatedButton.grid(row=1,column=0,sticky="WNE")
allocatedLabel.grid(row=0,column=1,sticky='NWS')
textFrame.grid(row=1,column=1,sticky="NESW")
scrollBar.pack(side=tk.RIGHT, fill=tk.Y)
readout.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)

readCSV() # run the inital read of csv to fill program with data
# run mainloop
root.mainloop()
 